export const SET_COMMENTS = "SET_COMMENTS";
export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export const GET_COMMENTS_LOADED = "GET_COMMENTS_LOADED";

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_LOADED = "GET_POSTS_LOADED";
export const SET_POSTS = "SET_POSTS";

export const GET_USERS = "GET_USERS";
export const SET_USERS = "SET_USERS";

export const SET_USERPOSTS = "SET_USERPOSTS"
export const GET_USERPOSTS_REQUEST = "GET_USERPOSTS_REQUEST"
export const GET_USERPOSTS_LOADED = "GET_USERPOSTS_LOADED"